# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 11:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170420_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
