# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170420_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={},
        ),
    ]
